### ISSUE TITLE
How to incorporate ligand parameter files in afnmr command line

### ISSUE THREAD

**Issue by KetanR24** [dacase/afnmr#9]
Dear Prof.,
I have created and trying to incorporate ligand parameter files (mol2 and frcmod), as you have instructed in the user manual, 

**afnmr -list "1" protein -frcmod ligand.frcmod -mol2 ligand.mol2**

but it says "Too many arguments". What mistake am I making? Kindly help me to write the command line properly with an example. 
Thanks

**Comment by dacase** [comment]
Thanks for the report.  The manual has a mistake about using the -mol2 command.  I've pushed a fix: do a git pull and look at the updated manual.  You will need to use -offlib instead of -mol2.

Second, the basename must be the last argument, after all options.  I've also made this requirement more explicit in the manual.

...hope this helps....dac
